all: rapport

rapport: 
	pdflatex TP1_MPNA_KERMARQUER_MAXIME.tex && pdflatex TP1_MPNA_KERMARQUER_MAXIME.tex && pdflatex TP1_MPNA_KERMARQUER_MAXIME.tex 

clean:
	rm -f *~ *.aux *.bbl *.blg *.log *.toc *.out
